spring:
  application:
    name: microservice-provider-demo
    
switchover: true
    
server:
  port: 11011
  
eureka: 
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
logging.file: /tmp/log/${spring.application.name}:${server.port}.log 
logging.pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx" 
  
  

